version: 2
jobs:
  build:
    docker:
    - image: lukaszlaszko/linux_build_tools:ubuntu_18.04
    steps:
    - checkout
    - run:
        name: "Pull Submodules"
        command: |
          git submodule init
          git submodule update --remote
    - run:
        name: Configure
        command: |
          rm -rf bin_debug && mkdir bin_debug
          cd bin_debug
          cmake -DCMAKE_BUILD_TYPE=Debug -DRELEASE_VERSION=0.0.0 ..
    - run:
        name: Build
        command: |
          cd bin_debug
          cmake --build . --target all
#    - run:
#        name: "Install dependencies"
#        command: |
#          cd bin_debug
#          cmake --build . --target install-dependencies
#    - run:
#        name: Test
#        command: |
#          cd bin_debug
#          cmake --build . --target install-dependencies
#          ctest --verbose
#    - deploy:
#        command: |
#          VERSION=$(python3.6 setup.py --version)
#
#          cd bin_debug
#          cmake --build . --target build-package
#
#          if [ "${CIRCLE_TAG}" == "${VERSION}" ]; then
#            PYPI_URL=${PYPI_TEST_URL}
#            PYPI_USERNAME=${PYPI_TEST_USERNAME}
#            PYPI_PASSWORD=${PYPI_TEST_PASSWORD}
#
#            twine upload --repository-url https://test.pypi.org/legacy/ -u ${PYPI_TEST_USERNAME} -p ${PYPI_TEST_PASSWORD} pysyscall_intercept.tar.gz
#          else
#            echo 'Branch name "${CIRCLE_TAG}" doesnt match "${VERSION}". Skipping pip upload.'
#          fi
#        filters:
#          tags:
#            only: /^(\d+\.)?(\d+\.)?(\*|\d+)/

